# Generated by Django 5.0.2 on 2025-08-21 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0002_extrafeetype_alter_extrafee_options_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur")),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide. Utilisez le format: +2376123456789', regex='^(\\+237|237)?[0-9]{10}$')], verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('GUARDIAN', 'Tuteur')], default='PARENT', max_length=20, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Hash du mot de passe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Utilisateur Parent',
                'verbose_name_plural': 'Utilisateurs Parents',
                'db_table': 'parents_portal_parentuser',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ParentPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('OM', 'Orange Money'), ('MOMO', 'MTN Mobile Money'), ('CARD', 'Carte bancaire'), ('BANK', 'Virement bancaire')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='parents_portal.parentuser')),
            ],
            options={
                'verbose_name': 'Méthode de Paiement',
                'verbose_name_plural': 'Méthodes de Paiement',
            },
        ),
        migrations.CreateModel(
            name='ParentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method_type', models.CharField(choices=[('OM', 'Orange Money'), ('MOMO', 'MTN Mobile Money'), ('CARD', 'Carte bancaire'), ('BANK', 'Virement bancaire')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_payments', to='students.student')),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_payments', to='finances.feetranche')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parents_portal.parentpaymentmethod')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parents_portal.parentuser')),
            ],
            options={
                'verbose_name': 'Paiement Parent',
                'verbose_name_plural': 'Paiements Parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('GRADE', 'Nouvelle note'), ('BULLETIN', 'Bulletin disponible'), ('PAYMENT', 'Paiement reçu'), ('REMINDER', 'Rappel de paiement'), ('ATTENDANCE', 'Absence'), ('GENERAL', 'Information générale')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parents_portal.parentuser')),
            ],
            options={
                'verbose_name': 'Notification Parent',
                'verbose_name_plural': 'Notifications Parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='parents_portal.parentuser')),
            ],
            options={
                'verbose_name': 'Session de Connexion Parent',
                'verbose_name_plural': 'Sessions de Connexion Parents',
            },
        ),
        migrations.CreateModel(
            name='ParentStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('TUTOR', 'Tuteur'), ('GUARDIAN', 'Responsable légal'), ('OTHER', 'Autre')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_view_academic', models.BooleanField(default=True)),
                ('can_view_financial', models.BooleanField(default=True)),
                ('can_make_payments', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='students.student')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relations', to='parents_portal.parentuser')),
            ],
            options={
                'verbose_name': 'Relation Parent-Étudiant',
                'verbose_name_plural': 'Relations Parent-Étudiant',
                'unique_together': {('parent_user', 'student')},
            },
        ),
    ]
