# Generated by Django 5.0.2 on 2025-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_guardian_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, help_text='Laissez vide pour génération automatique', max_length=20, unique=True),
        ),
    ]
