# Generated by Django 5.2.3 on 2025-09-09 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_schoolclass_name_en_and_more'),
        ('notes', '0001_initial'),
        ('students', '0003_alter_student_matricule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_date', models.DateField(verbose_name='Date du conseil')),
                ('president', models.CharField(max_length=100, verbose_name='Président du conseil')),
                ('secretary', models.CharField(blank=True, max_length=100, verbose_name='Secrétaire')),
                ('attendees', models.TextField(blank=True, verbose_name='Participants')),
                ('general_observations', models.TextField(blank=True, verbose_name='Observations générales')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Finalisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_councils', to='classes.schoolclass')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_councils', to='notes.trimester')),
            ],
            options={
                'verbose_name': 'Conseil de classe',
                'verbose_name_plural': 'Conseils de classe',
                'unique_together': {('school_class', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='ClassCouncilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('FELICITATIONS', 'Félicitations'), ('ENCOURAGEMENTS', 'Encouragements'), ('MISE_EN_GARDE_TRAVAIL', 'Mise en garde - Travail'), ('MISE_EN_GARDE_CONDUITE', 'Mise en garde - Conduite'), ('BLAME_TRAVAIL', 'Blâme - Travail'), ('BLAME_CONDUITE', 'Blâme - Conduite'), ('PASSAGE', 'Passage en classe supérieure'), ('REDOUBLEMENT', 'Redoublement'), ('ORIENTATION', 'Orientation'), ('EXCLUSION', 'Exclusion définitive')], max_length=30, verbose_name='Type de décision')),
                ('teacher_appreciation', models.TextField(blank=True, verbose_name='Appréciation des professeurs')),
                ('principal_appreciation', models.TextField(blank=True, verbose_name="Appréciation du chef d'établissement")),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('is_appeal_possible', models.BooleanField(default=True, verbose_name='Recours possible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='students.classcouncil')),
                ('next_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_students', to='classes.schoolclass', verbose_name='Classe suivante')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_decisions', to='students.student')),
            ],
            options={
                'verbose_name': 'Décision du conseil de classe',
                'verbose_name_plural': 'Décisions du conseil de classe',
                'unique_together': {('council', 'student')},
            },
        ),
    ]
