# Generated by Django 5.0.2 on 2025-08-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], help_text='Jour de la semaine (1=Lundi, ...).')),
                ('period', models.PositiveSmallIntegerField(help_text='Index du créneau dans la journée (ex: 1=8h-9h, 2=9h-10h, ...).')),
                ('duration', models.PositiveSmallIntegerField(default=1, help_text='Nombre de périodes consécutives occupées par ce créneau (ex: 2 pour 2h).')),
            ],
            options={
                'ordering': ['day', 'period'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name="Capacité d'accueil")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_teached', models.JSONField(blank=True, default=list, help_text='Liste des ids des matières enseignées dans la classe.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.schoollevel')),
            ],
            options={
                'verbose_name': 'Classe scolaire',
                'verbose_name_plural': 'Classes scolaires',
                'ordering': ['level', 'name', 'year'],
            },
        ),
    ]
