# Generated by Django 5.0.2 on 2025-08-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('school', '0001_initial'),
        ('subjects', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.school'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.schoolyear'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.school'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.schoolyear'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='class_obj',
            field=models.ForeignKey(help_text='Classe concernée par ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(help_text='Matière enseignée pendant ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(help_text='Enseignant affecté à ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='year',
            field=models.ForeignKey(help_text='Année scolaire du créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='school.schoolyear'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'level', 'year', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school_class', 'year', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('class_obj', 'year', 'day', 'period')},
        ),
    ]
