# Generated by Django 5.0.2 on 2025-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
