# Generated by Django 5.2.3 on 2025-09-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_schoolclass_name_en_schoolclass_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='schoolclass',
            name='name_fr',
        ),
    ]
