# Generated by Django 5.2.3 on 2025-09-10 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_schoolclass_name_en_and_more'),
        ('students', '0004_classcouncil_classcouncildecision'),
        ('subjects', '0004_alter_lesson_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la présence')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'Retard'), ('excused', 'Absence justifiée')], default='present', help_text='Statut de présence', max_length=10)),
                ('remark', models.TextField(blank=True, help_text='Remarque sur la présence', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a enregistré la présence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(help_text="Classe de l'élève", on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.schoolclass')),
                ('student', models.ForeignKey(help_text='Élève concerné par cette présence', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
                ('subject', models.ForeignKey(help_text='Matière concernée', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
