# Generated by Django 5.2.3 on 2025-09-10 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_attendance'),
        ('students', '0004_classcouncil_classcouncildecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentConvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocation_reason', models.CharField(choices=[('comportement', 'Problème de comportement'), ('resultats', 'Résultats scolaires'), ('assiduite', "Problème d'assiduité"), ('autre', 'Autre motif')], help_text='Motif de la convocation', max_length=20)),
                ('details', models.TextField(help_text='Détails de la convocation')),
                ('proposed_datetime', models.DateTimeField(help_text='Date et heure proposées')),
                ('meeting_person', models.CharField(help_text='Personne qui recevra les parents', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('completed', 'Effectuée'), ('cancelled', 'Annulée')], default='pending', help_text='Statut de la convocation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a enregistré la convocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_convocations', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(help_text="Classe de l'élève", on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='classes.schoolclass')),
                ('student', models.ForeignKey(help_text='Élève concerné', on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='students.student')),
            ],
            options={
                'verbose_name': 'Convocation parent',
                'verbose_name_plural': 'Convocations parents',
                'ordering': ['-proposed_datetime', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('avertissement', 'Avertissement'), ('retenue', 'Retenue'), ('exclusion', 'Exclusion temporaire'), ('conseil', 'Conseil de discipline')], help_text='Type de sanction', max_length=20)),
                ('reason', models.TextField(help_text='Motif de la sanction')),
                ('sanction_date', models.DateField(help_text='Date de la sanction')),
                ('duration', models.CharField(blank=True, help_text='Durée (pour retenue/exclusion)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a enregistré la sanction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sanctions', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(help_text="Classe de l'élève", on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='classes.schoolclass')),
                ('student', models.ForeignKey(help_text='Élève sanctionné', on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='students.student')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['-sanction_date', 'student__last_name'],
            },
        ),
    ]
