# Generated by Django 5.0.2 on 2025-08-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom du système')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du système')),
            ],
            options={
                'verbose_name': 'Système éducatif',
                'verbose_name_plural': 'Systèmes éducatifs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du ministère')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du ministère')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Ministère de tutelle',
                'verbose_name_plural': 'Ministères de tutelle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du type')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du type')),
            ],
            options={
                'verbose_name': "Type d'établissement",
                'verbose_name_plural': "Types d'établissements",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9, unique=True, verbose_name='Année scolaire')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTUREE', 'Clôturée')], default='EN_COURS', max_length=10)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='RegionalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la délégation')),
                ('region', models.CharField(max_length=50, verbose_name='Région')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='school.ministry', verbose_name='Ministère de tutelle')),
            ],
            options={
                'verbose_name': 'Délégation régionale',
                'verbose_name_plural': 'Délégations régionales',
                'ordering': ['region', 'name'],
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='DocumentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'en-tête")),
                ('is_default', models.BooleanField(default=False, verbose_name='En-tête par défaut')),
                ('school_name', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('school_motto', models.CharField(blank=True, max_length=200, verbose_name="Devise de l'école")),
                ('school_address', models.TextField(verbose_name="Adresse de l'école")),
                ('school_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone de l'école")),
                ('school_email', models.EmailField(blank=True, max_length=254, verbose_name="Email de l'école")),
                ('school_website', models.URLField(blank=True, verbose_name="Site web de l'école")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name="Logo de l'école")),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature du directeur')),
                ('stamp', models.ImageField(blank=True, null=True, upload_to='stamps/', verbose_name="Tampon de l'école")),
                ('authorization_number', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'autorisation")),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('director_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du directeur')),
                ('director_title', models.CharField(blank=True, max_length=100, verbose_name='Titre du directeur')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_headers', to='school.ministry', verbose_name='Ministère de tutelle')),
                ('regional_delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_headers', to='school.regionaldelegation', verbose_name='Délégation régionale')),
            ],
            options={
                'verbose_name': 'En-tête de document',
                'verbose_name_plural': 'En-têtes de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du niveau')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school.educationsystem', verbose_name='Système éducatif')),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['system', 'order', 'name'],
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name="Code de l'établissement")),
                ('authorization_number', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'autorisation")),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_schools', to='school.documentheader', verbose_name='En-tête par défaut')),
                ('education_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school.educationsystem', verbose_name='Système éducatif')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='school.ministry', verbose_name='Ministère de tutelle')),
                ('regional_delegation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='school.regionaldelegation', verbose_name='Délégation régionale')),
                ('levels', models.ManyToManyField(related_name='schools', to='school.schoollevel', verbose_name='Niveaux enseignés')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school.schooltype', verbose_name="Type d'établissement")),
            ],
            options={
                'verbose_name': 'Établissement scolaire',
                'verbose_name_plural': 'Établissements scolaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_current', to='school.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='YearClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cloture', models.DateTimeField(auto_now_add=True)),
                ('nouvelle_annee', models.CharField(max_length=9, verbose_name='Nouvelle année scolaire')),
                ('annee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloture', to='school.schoolyear')),
            ],
        ),
    ]
