# Generated by Django 5.0.2 on 2025-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationsystem',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nom du système'),
        ),
        migrations.AddField(
            model_name='educationsystem',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Nom du système'),
        ),
        migrations.AddField(
            model_name='school',
            name='code_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name="Code de l'établissement"),
        ),
        migrations.AddField(
            model_name='school',
            name='code_fr',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name="Code de l'établissement"),
        ),
        migrations.AddField(
            model_name='school',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Nom de l'établissement"),
        ),
        migrations.AddField(
            model_name='school',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name="Nom de l'établissement"),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom du niveau'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom du niveau'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='annee_en',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='annee_fr',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='Année scolaire'),
        ),
    ]
