# Generated by Django 5.0.2 on 2025-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_educationsystem_name_en_educationsystem_name_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationsystem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='educationsystem',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='school',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='school',
            name='code_fr',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='schoollevel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='schoollevel',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='annee_en',
        ),
        migrations.RemoveField(
            model_name='schoolyear',
            name='annee_fr',
        ),
        migrations.CreateModel(
            name='MatriculeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(choices=[('STUDENT', 'Élève'), ('TEACHER', 'Enseignant'), ('CLASS', 'Classe')], max_length=20, verbose_name='Type de séquence')),
                ('prefix', models.CharField(help_text='Préfixe du matricule (ex: STU, TCH)', max_length=10, verbose_name='Préfixe')),
                ('current_year', models.PositiveIntegerField(help_text='Année pour laquelle la séquence est active', verbose_name='Année courante')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro utilisé')),
                ('format_pattern', models.CharField(default='{prefix}{year}{number:04d}', help_text='Format: {prefix} pour préfixe, {year} pour année, {number} pour numéro séquentiel', max_length=50, verbose_name='Format du matricule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séquence de matricule',
                'verbose_name_plural': 'Séquences de matricules',
                'ordering': ['sequence_type', 'current_year'],
                'unique_together': {('sequence_type', 'current_year')},
            },
        ),
    ]
