# Generated by Django 5.0.2 on 2025-08-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_educationsystem_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matriculesequence',
            options={'ordering': ['sequence_type'], 'verbose_name': 'Séquence de matricule', 'verbose_name_plural': 'Séquences de matricules'},
        ),
        migrations.AlterUniqueTogether(
            name='matriculesequence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matriculesequence',
            name='auto_generation',
            field=models.BooleanField(default=True, help_text='Générer automatiquement les matricules', verbose_name='Génération automatique'),
        ),
        migrations.AlterField(
            model_name='matriculesequence',
            name='sequence_type',
            field=models.CharField(choices=[('STUDENT', 'Élève'), ('TEACHER', 'Enseignant')], max_length=20, unique=True, verbose_name='Type de séquence'),
        ),
    ]
