# Generated by Django 5.0.2 on 2025-08-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('school', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationality', models.CharField(default='Camerounaise', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('main_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_teachers', to='subjects.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Coefficient de la matière pour le calcul des moyennes')),
                ('hours_per_week', models.FloatField(default=0, help_text="Nombre d'heures par semaine pour cette matière")),
                ('school_class', models.ForeignKey(help_text='Classe concernée par cette affectation', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='classes.schoolclass')),
                ('subject', models.ForeignKey(help_text='Matière enseignée', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subjects.subject')),
                ('teacher', models.ForeignKey(blank=True, help_text='Enseignant affecté à cette classe pour cette matière', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
                ('year', models.ForeignKey(help_text="Année scolaire de l'affectation", on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='school.schoolyear')),
            ],
            options={
                'verbose_name': "Affectation d'enseignement",
                'verbose_name_plural': "Affectations d'enseignement",
                'ordering': ['school_class', 'subject', 'teacher'],
                'unique_together': {('teacher', 'subject', 'school_class', 'year')},
            },
        ),
    ]
