# Generated by Django 5.0.2 on 2025-08-15 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.CharField(choices=[('1ER', '1er Trimestre'), ('2EME', '2ème Trimestre'), ('3EME', '3ème Trimestre')], max_length=4, verbose_name='Trimestre')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimesters', to='school.school')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimesters', to='school.schoolyear')),
            ],
            options={
                'verbose_name': 'Trimestre',
                'verbose_name_plural': 'Trimestres',
                'ordering': ['trimester'],
                'unique_together': {('trimester', 'year', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(choices=[('EVAL1', 'Évaluation 1 (1er Trimestre)'), ('EVAL2', 'Évaluation 2 (1er Trimestre)'), ('EVAL3', 'Évaluation 3 (2ème Trimestre)'), ('EVAL4', 'Évaluation 4 (2ème Trimestre)'), ('EVAL5', 'Évaluation 5 (3ème Trimestre)'), ('EVAL6', 'Évaluation 6 (3ème Trimestre)')], max_length=5, verbose_name="Type d'évaluation")),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Note maximale')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient')),
                ('eval_date', models.DateField(verbose_name="Date de l'évaluation")),
                ('duration', models.PositiveIntegerField(default=60, help_text='Durée en minutes', verbose_name='Durée')),
                ('instructions', models.TextField(blank=True, help_text="Instructions pour l'évaluation")),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouverte pour saisie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='classes.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='subjects.subject')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='notes.trimester')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-eval_date'],
                'unique_together': {('eval_type', 'trimester', 'subject', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_size', models.PositiveIntegerField(verbose_name='Effectif de la classe')),
                ('student_rank', models.PositiveIntegerField(verbose_name="Rang de l'élève")),
                ('class_average', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne de la classe')),
                ('student_average', models.DecimalField(decimal_places=2, max_digits=4, verbose_name="Moyenne de l'élève")),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total des points')),
                ('total_coefficients', models.PositiveIntegerField(verbose_name='Total des coefficients')),
                ('success_rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Taux de réussite (%)')),
                ('appreciation', models.TextField(blank=True, help_text='Appréciation générale')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bulletins', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bulletins', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='students.student')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='notes.trimester')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['student_rank'],
                'unique_together': {('student', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='BulletinLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Coefficient')),
                ('average', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne')),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total des points')),
                ('max_coefficient_rank', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Max Coef Rangs')),
                ('class_average_percent', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Moy. Cla %')),
                ('appreciation', models.CharField(blank=True, help_text='Appréciation de la matière', max_length=255)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='notes.bulletin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletin',
                'unique_together': {('bulletin', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note')),
                ('remarks', models.TextField(blank=True, help_text='Commentaires du professeur')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='notes.evaluation')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': "Note d'étudiant",
                'verbose_name_plural': "Notes d'étudiants",
                'ordering': ['-graded_at'],
                'unique_together': {('student', 'evaluation')},
            },
        ),
    ]
