# Generated by Django 5.0.2 on 2025-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.PositiveIntegerField(choices=[(1, 'Groupe 1'), (2, 'Groupe 2')], default=1, verbose_name='Groupe')),
            ],
        ),
    ]
