# Generated by Django 5.0.2 on 2025-08-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('subjects', '0003_alter_subject_options_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, help_text='Créneau horaire réservé pour cette leçon (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='classes.timetableslot', verbose_name='Créneau horaire'),
        ),
    ]
