# Generated by Django 5.0.2 on 2025-08-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='classes.schoolclass')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='students.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='school.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Frais d'inscription")),
                ('tuition_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais de scolarité total')),
                ('tranche_count', models.PositiveIntegerField(default=3, verbose_name='Nombre de tranches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='classes.schoolclass')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='FeeTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numéro de tranche')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='finances.feestructure')),
            ],
            options={
                'ordering': ['fee_structure', 'number'],
                'unique_together': {('fee_structure', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('granted_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='students.student')),
                ('tranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finances.feetranche')),
            ],
        ),
        migrations.CreateModel(
            name='Moratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant concerné')),
                ('new_due_date', models.DateField(verbose_name="Nouvelle date d'échéance")),
                ('reason', models.TextField(verbose_name='Motif du moratoire')),
                ('is_approved', models.BooleanField(default=False, verbose_name="Validé par l'administration")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_moratoriums', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moratoriums', to='students.student')),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moratoriums', to='finances.feetranche')),
            ],
        ),
        migrations.CreateModel(
            name='TranchePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money'), ('virement', 'Virement')], max_length=30)),
                ('receipt', models.CharField(blank=True, max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='finances/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_payments', to='students.student')),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.feetranche')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('refund_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='finances.tranchepayment')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money'), ('virement', 'Virement')], max_length=30)),
                ('receipt', models.CharField(blank=True, max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='finances/inscription_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_payments', to='finances.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_payments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'fee_structure')},
            },
        ),
    ]
