# Generated by Django 5.0.2 on 2025-08-16 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('finances', '0001_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type de frais')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de frais annexe',
                'verbose_name_plural': 'Types de frais annexes',
            },
        ),
        migrations.AlterModelOptions(
            name='extrafee',
            options={'ordering': ['name', 'year'], 'verbose_name': 'Frais annexe', 'verbose_name_plural': 'Frais annexes'},
        ),
        migrations.RemoveField(
            model_name='extrafee',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='extrafee',
            name='student',
        ),
        migrations.AddField(
            model_name='extrafee',
            name='amounts_by_class',
            field=models.JSONField(blank=True, default=dict, help_text='Montants spécifiques par classe (classe_id: montant)', verbose_name='Montants par classe'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='apply_to_all_classes',
            field=models.BooleanField(default=False, verbose_name='Appliquer à toutes les classes'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='extra_fees', to='classes.schoolclass', verbose_name='Classes concernées'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='exam_types',
            field=models.JSONField(blank=True, default=list, help_text="Liste des types d'examens (BEPC, Probatoire, Bac)", verbose_name="Types d'examens"),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='is_exam_fee',
            field=models.BooleanField(default=False, verbose_name="Frais d'examen"),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Facultatif'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='extrafee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par défaut'),
        ),
        migrations.AlterField(
            model_name='extrafee',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='extrafee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du frais'),
        ),
        migrations.AlterField(
            model_name='extrafee',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='school.schoolyear', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='extrafee',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_fees', to='finances.extrafeetype', verbose_name='Type de frais'),
        ),
        migrations.CreateModel(
            name='ExtraFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Date de paiement')),
                ('mode', models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Money'), ('virement', 'Virement')], max_length=30, verbose_name='Mode de paiement')),
                ('receipt', models.CharField(blank=True, max_length=50, verbose_name='Numéro de reçu')),
                ('document', models.FileField(blank=True, null=True, upload_to='finances/extra_fee_receipts/', verbose_name='Document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extra_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.extrafee', verbose_name='Frais annexe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fee_payments', to='students.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Paiement frais annexe',
                'verbose_name_plural': 'Paiements frais annexes',
                'unique_together': {('student', 'extra_fee')},
            },
        ),
    ]
